sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
