
include $(APPDIR)/Make.defs
include $(SDKDIR)/Make.defs

PROGNAME = $(CONFIG_EXAMPLES_CXD5602PWBIMU_LOGGER_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_CXD5602PWBIMU_LOGGER_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_CXD5602PWBIMU_LOGGER_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_CXD5602PWBIMU_LOGGER)

ASRCS =
CSRCS = log_server.c
MAINSRC = cxd5602pwbimu_logger_main.c

include $(APPDIR)/Application.mk
