#define STRINGCASE(e) case AL_EVENT_##e: return #e;

static const char *convert_evtid(int id)
{
  switch (id)
    {
      STRINGCASE(OVERFLOW)
      STRINGCASE(UNDERFLOW)
      STRINGCASE(ILLIGALSTREAM)
      STRINGCASE(UNSUPPORTFMT)
      STRINGCASE(DECODEDONE)
      STRINGCASE(STREAMDONE)
      STRINGCASE(PLAYSTARTED)
      STRINGCASE(PLAYSTOPPED)
      STRINGCASE(RECORDSTARTED)
      STRINGCASE(RECORDSTOPPED)
      STRINGCASE(PLAYPAUSED)
      STRINGCASE(PLAYRESUMED)
      STRINGCASE(RECORDPAUSED)
      STRINGCASE(RECORDRESUMED)
      STRINGCASE(DRVERROR)
      STRINGCASE(INVALIDSYSPARAM)
      STRINGCASE(STOPOUTPUT)
      STRINGCASE(STOPINPUT)
      STRINGCASE(INITERROR)
      STRINGCASE(SENDERROR)
      STRINGCASE(MP3FRAMEINFO)
      STRINGCASE(MP3DECWORKEREND)
      STRINGCASE(MP3DECUNKNOWNEVT)
      STRINGCASE(MP3DECERROR)
      STRINGCASE(MP3DEC_WRONGTYPE)
      STRINGCASE(MP3DEC_WRONGVER)
      default:
        return "not event id...";
    }
}
