#
# This is empty and for through make targets from NuttX build system.
#

.PHONY: all dirlinks preconfig context depend clean distclean
all:
dirlinks:
preconfig:
context:
depend:
clean:
distclean:
libapps.a:
