############################################################################
# rs422/Makefile
############################################################################

include $(APPDIR)/Make.defs

# RS422 built-in application info
PROGNAME  = $(CONFIG_EXAMPLES_RS422_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_RS422_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_RS422_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_RS422)

# RS422 Example
ASRCS =
CSRCS = 
MAINSRC = rs422_main.c

include $(APPDIR)/Application.mk
