#!/usr/bin/env python3
############################################################################
# tools/mkkconfig.py
#
#   Copyright 2020 Sony Semiconductor Solutions Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
# 3. Neither the name of Sony Semiconductor Solutions Corporation nor
#    the names of its contributors may be used to endorse or promote
#    products derived from this software without specific prior written
#    permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
############################################################################

import os
import argparse

header='''
#
# For a description of the syntax of this configuration file,
# see the file kconfig-language.txt in the NuttX tools repository.
#
# This file is autogenerated, do not edit.
#

'''

KCONFIG='Kconfig'

parser = argparse.ArgumentParser(description='Create Kconfig for SDK repository')
parser.add_argument('-m', dest='menudesc', help='Menu description')
parser.add_argument('-o', dest='outfile', help='Output file name')
parser.add_argument('directory', metavar='DIR', type=str, nargs='+',
                    help='Directories to add to Kconfig')
args = parser.parse_args()

if args.outfile:
    KCONFIG = args.outfile

f = open(KCONFIG, 'w')
f.write(header)

if args.menudesc:
    f.write('menu "%s"\n' % args.menudesc)

for d in args.directory:
    p = os.path.join(os.path.realpath(d), "Kconfig")
    if os.path.exists(p):
        f.write('source "%s"\n' % p)

if args.menudesc:
    f.write('endmenu # %s\n' % args.menudesc)

f.close()
